// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: protoFile/favorite.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Favorite_FavortieAction_FullMethodName = "/service.Favorite/FavortieAction"
	Favorite_FavortieList_FullMethodName   = "/service.Favorite/FavortieList"
)

// FavoriteClient is the client API for Favorite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FavoriteClient interface {
	FavortieAction(ctx context.Context, in *TiktokFavoriteActionRequest, opts ...grpc.CallOption) (*TiktokFavoriteActionResponse, error)
	FavortieList(ctx context.Context, in *TiktokFavoriteListRequest, opts ...grpc.CallOption) (*TiktokFavoriteListResponse, error)
}

type favoriteClient struct {
	cc grpc.ClientConnInterface
}

func NewFavoriteClient(cc grpc.ClientConnInterface) FavoriteClient {
	return &favoriteClient{cc}
}

func (c *favoriteClient) FavortieAction(ctx context.Context, in *TiktokFavoriteActionRequest, opts ...grpc.CallOption) (*TiktokFavoriteActionResponse, error) {
	out := new(TiktokFavoriteActionResponse)
	err := c.cc.Invoke(ctx, Favorite_FavortieAction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favoriteClient) FavortieList(ctx context.Context, in *TiktokFavoriteListRequest, opts ...grpc.CallOption) (*TiktokFavoriteListResponse, error) {
	out := new(TiktokFavoriteListResponse)
	err := c.cc.Invoke(ctx, Favorite_FavortieList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FavoriteServer is the server API for Favorite service.
// All implementations must embed UnimplementedFavoriteServer
// for forward compatibility
type FavoriteServer interface {
	FavortieAction(context.Context, *TiktokFavoriteActionRequest) (*TiktokFavoriteActionResponse, error)
	FavortieList(context.Context, *TiktokFavoriteListRequest) (*TiktokFavoriteListResponse, error)
	mustEmbedUnimplementedFavoriteServer()
}

// UnimplementedFavoriteServer must be embedded to have forward compatible implementations.
type UnimplementedFavoriteServer struct {
}

func (UnimplementedFavoriteServer) FavortieAction(context.Context, *TiktokFavoriteActionRequest) (*TiktokFavoriteActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FavortieAction not implemented")
}
func (UnimplementedFavoriteServer) FavortieList(context.Context, *TiktokFavoriteListRequest) (*TiktokFavoriteListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FavortieList not implemented")
}
func (UnimplementedFavoriteServer) mustEmbedUnimplementedFavoriteServer() {}

// UnsafeFavoriteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FavoriteServer will
// result in compilation errors.
type UnsafeFavoriteServer interface {
	mustEmbedUnimplementedFavoriteServer()
}

func RegisterFavoriteServer(s grpc.ServiceRegistrar, srv FavoriteServer) {
	s.RegisterService(&Favorite_ServiceDesc, srv)
}

func _Favorite_FavortieAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TiktokFavoriteActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServer).FavortieAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Favorite_FavortieAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServer).FavortieAction(ctx, req.(*TiktokFavoriteActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Favorite_FavortieList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TiktokFavoriteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavoriteServer).FavortieList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Favorite_FavortieList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavoriteServer).FavortieList(ctx, req.(*TiktokFavoriteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Favorite_ServiceDesc is the grpc.ServiceDesc for Favorite service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Favorite_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.Favorite",
	HandlerType: (*FavoriteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FavortieAction",
			Handler:    _Favorite_FavortieAction_Handler,
		},
		{
			MethodName: "FavortieList",
			Handler:    _Favorite_FavortieList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoFile/favorite.proto",
}
